# Generated by Django 5.1.2 on 2024-10-15 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Viper', '0002_auto_delete_mimodelo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auto',
            old_name='nombre',
            new_name='modelo',
        ),
        migrations.AddField(
            model_name='auto',
            name='año',
            field=models.IntegerField(default=2024),
        ),
    ]
