# Generated by Django 5.1.2 on 2024-10-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Viper', '0003_rename_nombre_auto_modelo_auto_año'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='marca',
            field=models.CharField(default='Dodge', max_length=100),
        ),
    ]
