# Generated by Django 5.1.2 on 2024-10-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Viper', '0004_auto_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('año', models.IntegerField()),
                ('altitud', models.IntegerField()),
            ],
        ),
    ]
