# Generated by Django 5.1.2 on 2024-10-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Viper', '0008_avion_foto_alter_auto_año_alter_auto_hp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='foto_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
