# Generated by Django 5.1.2 on 2024-10-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Viper', '0009_auto_foto_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='avion',
            name='foto_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
